services:
  s2admin:
    image: dpage/pgadmin4:latest
    container_name: 68-s2-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    networks:
      - backend
networks:
  backend:
    driver: bridge